zopefoundation/zope.interface

- setup.py
rather than pointing at itself, which isn't very useful.
> setup.py: Make URL on PyPI point to GitHub

- README.rst
I find it handy to be able to flip back and forth easily between the source code repo and PyPI.
Preview at https://github.com/msabramo/zope.interface/blob/add_pypi_badge/README.rst
> README.rst: Add PyPI latest version badge

- setup.py
> Make zope.interface installable on Py3.5 w/o a C compiler

- README.rst
- appveyor.yml
As per [their blog post of the 27th April](https://blog.readthedocs.com/securing-subdomains/) ‘Securing subdomains’:
> Starting today, Read the Docs will start hosting projects from subdomains on the domain readthedocs.io, instead of on readthedocs.org. This change addresses some security concerns around site cookies while hosting user generated data on the same domain as our dashboard.
Test Plan: Manually visited all the links I’ve modified.
> Convert readthedocs link for their .org -> .io migration for hosted projects

- src/zope/interface/_compat.py
- src/zope/interface/adapter.py
- src/zope/interface/interfaces.py
- src/zope/interface/registry.py
- src/zope/interface/tests/test_adapter.py
- src/zope/interface/tests/test_declarations.py
- src/zope/interface/tests/test_interface.py
- src/zope/interface/tests/test_registry.py
Since we no longer support 3.2 we can use the literal syntax.
This was done with a quick sed script.
> Remove the _u compat function.

- CHANGES.rst
- setup.py
Uses `find_packages` instead of a manual list.
Fixes #13.
Fixes #14.
> Make setuptools a hard dependency of setup.py

- README.rst
docs.zope.org has now a redirect.
> Use the canonical URL.

- .coveragerc
- CHANGES.rst
- src/zope/interface/registry.py
- src/zope/interface/tests/test_registry.py
Fixes #46.
Benchmarks show a dramatic improvement; not quite as good as the demonstration in #46 because the implementation had to be a bit more complex to properly handle unregistration, but still very good. Here it is with 20,000 items already registered:
```
%time add_to_reg(reg, 1000)
CPU times: user 190 ms, sys: 19.3 ms, total: 209 ms
Wall time: 203 ms
```
Here's a profile with about 100,000 utilities registered:
```
%prun add_to_reg(reg, 1000)
80005 function calls (79005 primitive calls) in 0.713 seconds
Ordered by: internal time
ncalls  tottime  percall  cumtime  percall filename:lineno(function)
1000    0.596    0.001    0.621    0.001 adapter.py:202(subscribe)
12000    0.016    0.000    0.019    0.000 interface.py:518(__hash__)
1000    0.010    0.000    0.709    0.001 …
```
> Use dictionary lookups for testing subscribed status.

- CHANGES.rst
- src/zope/interface/registry.py
- src/zope/interface/tests/test_registry.py
Fixes #53.
This depends on the `id` of the instance staying stable and not being reused while the instance is extant. It uses a manual weakref and cleanup function.
> Support Components subclasses that are not hashable.

- CHANGES.rst
- src/zope/interface/declarations.py
- src/zope/interface/tests/test_declarations.py
Do this by removing the `__eq__` and `__ne__` methods and allowing the interpreter to reverse the operands if needed.
Fixes #55.
> Fix equality testing of implementedBy objects that have been proxied.

- CHANGES.rst
- src/zope/interface/_zope_interface_coptimizations.c
- src/zope/interface/adapter.py
- src/zope/interface/declarations.py
- src/zope/interface/interface.py
- src/zope/interface/tests/test_adapter.py
- src/zope/interface/tests/test_declarations.py
- src/zope/interface/tests/test_interface.py
- The bare import of `_zope_c_optimizations` prevented them from being   used.
- After enabling them via absolute imports, they would fail due to http://bugs.python.org/issue15657.
Fixes #60.
> Fix C optimizations broken on Py3k.

- setup.cfg
> Ensure that LICENSE.txt is present in built wheels.

- CHANGES.rst
- src/zope/interface/_zope_interface_coptimizations.c
Instead, use the intended METH_KEYWORDS | METH_VARARGS spelling.
Fixes #71  and avoids a complier warning on 3.6 and below.
(There are some automatic trailing whitespace removals; `?w=0` might be helpful when viewing.)
> Don't redefine METH_KEYWORDS

- docs/README.rst
Classes (factories) _implement_, objects _provide_. After first carefully explaining the difference, the docs mix them up.
> Fix sentence in README

- .coveragerc
- .gitignore
- .manylinux-install.sh
- .manylinux.sh
- .travis.yml
- MANIFEST.in
- appveyor.yml
- setup.py
- src/zope/interface/tests/test_odd_declarations.py
- tox.ini
Copied from master branch, but removed the Python 3 stuff, which is unsupported on the 3.6 branch. Well, 3.1 seems supported, but that is very old, and on 3.3 I got errors locally.
Also removed 'docs' from the tox envs, as that proved tricky to get to work, and has changed much.
Removed `TODO_test_classProvides_fails_for_odd_class` test method, which would always fail but be ignored due to its name, except that the coverage tests would *not* ignore it, leading to a failure.
> Added Travis, appveyor, and tox for 3.6 branch.

- .coveragerc
- CHANGES.rst
- src/zope/interface/_zope_interface_coptimizations.c
- src/zope/interface/adapter.py
- src/zope/interface/interfaces.py
- src/zope/interface/tests/test_adapter.py
Prevents corruption of lookup cache.
Alternative to fix proposed in #75.
> Disallow non-text name passed to adapter registry methods.

- CHANGES.rst
- src/zope/interface/registry.py
- src/zope/interface/tests/test_registry.py
simplification, avoids spurious test failures when checking for
leaks in tests with persistent registries.
This fixes #83
> Simply the caching of utility-registration data. In addition to

- .coveragerc
- .gitignore
- src/zope/interface/_compat.py
- src/zope/interface/common/tests/test_idatetime.py
- src/zope/interface/common/tests/test_import_interfaces.py
- src/zope/interface/tests/__init__.py
- src/zope/interface/tests/odd.py
- src/zope/interface/tests/test_adapter.py
- src/zope/interface/tests/test_advice.py
- src/zope/interface/tests/test_declarations.py
- src/zope/interface/tests/test_document.py
- src/zope/interface/tests/test_element.py
- src/zope/interface/tests/test_interface.py
- src/zope/interface/tests/test_interfaces.py
- src/zope/interface/tests/test_odd_declarations.py
- src/zope/interface/tests/test_registry.py
- src/zope/interface/tests/test_sorting.py
- src/zope/interface/tests/test_verify.py
- tox.ini
Partially addresses #87
- Remove manual lists of tests in favor of loadTestsFromName. This mostly gets all test runners running the same number of tests.
- Remove `additional_tests`, which was just duplicating the discovered tests. No modern test runner seems to need it.
- Change the two compatibility skip decorators to actually use unitetest skips, which helps with the reporting.
- Pull in the .gitignore and .coveragerc changes from #86.
> Test sanity cleanups

- .travis.yml
Test coverage is not at 100% yet so it should fail this PR (I'll address coverage in a future PR; doing so now would have a small conflict with #86).
Also enable pip caching since we are installing more deps.
Update PyPy versions to latest available for speed and because the old version of PyPy3 can't install newer pip and coverage, etc.
Partially addresses #87
> Enable coveralls

- .coveragerc
- src/zope/interface/adapter.py
- src/zope/interface/advice.py
- src/zope/interface/declarations.py
- src/zope/interface/interface.py
- src/zope/interface/tests/advisory_testing.py
- src/zope/interface/tests/dummy.py
- src/zope/interface/tests/odd.py
- src/zope/interface/tests/test_adapter.py
- src/zope/interface/tests/test_advice.py
- src/zope/interface/tests/test_declarations.py
- src/zope/interface/tests/test_interface.py
- src/zope/interface/tests/test_registry.py
- src/zope/interface/tests/test_verify.py
- src/zope/interface/verify.py
- tox.ini
Well, as close as possible without conflicting with #86.
This is almost entirely trivial changes:
- Make dummy methods that should never be called either raise NotImplementedError or call self.fail() in tests.
- Standardize the no-coverage pragma
- Add a few pragmas where coverage varies across versions/implementations, mostly for the sake of tox (travis should hit them all).
Also convert the tox command to use the `coverage` command and drop use of `nosetests`. This also drops generating the .xml coverage reports by default.
> 100% coverage

- CHANGES.rst
- src/zope/interface/registry.py
- src/zope/interface/tests/test_registry.py
This is an alternative to #86 and was suggested by @mgedmin in #85.
There are tests to be sure this works for subclasses like Pyramid's Registry that extend dict too.
This doesn't change the pickle format, we were storing the output of `object.__reduce__` previously.
I've verified this fixes the zc.catalog issue.
> Fix #85 by implementing __reduce__ to omit _v_ attributes.

- .coveragerc
- .gitignore
- src/zope/interface/_compat.py
- src/zope/interface/adapter.py
- src/zope/interface/advice.py
- src/zope/interface/declarations.py
- src/zope/interface/interface.py
- src/zope/interface/tests/advisory_testing.py
- src/zope/interface/tests/odd.py
- src/zope/interface/tests/test_adapter.py
- src/zope/interface/tests/test_declarations.py
- src/zope/interface/tests/test_exceptions.py
- src/zope/interface/tests/test_interface.py
- src/zope/interface/tests/test_odd_declarations.py
- src/zope/interface/verify.py
- tox.ini
Fixes #91
Remove many (or most) now-redundant 'pragma: no cover'.
A few minor test changes to get full branch coverage.
> Enable combined coverage reports under tox and branch coverage

- CHANGES.rst
- src/zope/interface/_zope_interface_coptimizations.c
call PyObject_GC_UnTrack() in tp_dealloc()
see the following sites for details:
* https://bugs.python.org/issue31095
* https://github.com/python/cpython/pull/2974
> Fix process of reference count during GC

- CHANGES.rst
- src/zope/interface/adapter.py
- src/zope/interface/tests/test_adapter.py
Fixes #12 - registering instance methods as listeners doesn’t allow to easily unregister them as the registry tries to find the handler with 'is' but it should use '==' to allow the python BoundMethod wrapper (which is a new instance every time instance.$methodname is accessed).
> Allow Registering and unregistering instance methods as listeners

- .travis.yml
Now that Travis has again upped its PyPy game, these should not be pinned to specific versions, but rather float with the PyPy releases.
> Let pypy and pypy3 float on Travis

- docs/conf.py
See http://www.sphinx-doc.org/en/stable/config.html#confval-latex_engine
Ought to fix #111, provided that ReadTheDocs supports LuaLaTeX.
> Use LuaLaTeX for PDF docs

- src/zope/__init__.py
We *do* have a dependency on setuptools, so the try/except block should be unnecessary. At worst it might hide installation errors.
Fixes #114.
> Synchronize and simplify zope/__init__.py

- docs/api.rst
- docs/conf.py
- src/zope/interface/common/idatetime.py
- src/zope/interface/common/interfaces.py
- src/zope/interface/common/mapping.py
- src/zope/interface/common/sequence.py
I was working on documenting another project and wanted to link to them (especially zope.interface.common.idatetime) but discovered they weren't published.
This makes the API page even longer and more unwieldy. I'm working on a followup PR that splits it into more manageable chunks.
> Publish the documentation for zope.interface.common

- docs/api/adapters.rst
- docs/api/common.rst
- docs/api/components.rst
- docs/api/declarations.rst
- docs/api/index.rst
- docs/api/specifications.rst
- docs/index.rst
- src/zope/interface/declarations.py
- src/zope/interface/interface.py
- src/zope/interface/interfaces.py
The promised follow up to #120. This breaks the reference documentation into four major categories, and then groups things further within those categories. Copious amounts of cross references were inserted (or made clickable). A number of neglected objects were added to the documentation (E.g., the component events).
Hopefully this makes things easier to follow (it does for me).
> Reorganize API docs

- rtd.txt
See https://github.com/zopefoundation/zope.interface/pull/121#issuecomment-406372435
> Make rtd.txt install the checked out code, not the version from PyPI [skip ci]

- .coveragerc
- CHANGES.rst
- src/zope/interface/tests/test_verify.py
- src/zope/interface/verify.py
> Fix 'verifyObject' for class objects with staticmethods on Python 3.

- CHANGES.rst
- src/zope/interface/interface.py
- src/zope/interface/tests/test_interface.py
provides query/get/list taggedvalue with subclass inheritance
fix: https://github.com/plone/plone.dexterity/issues/57 and similar issues
> provides taggedvalue inheritance

- .manylinux-install.sh
- .manylinux.sh
- .travis.yml
This PR makes it so we _always_ build manylinux wheels, but only upload
them for git tags.
Highlights:
- Move regular Linux Python builds outside the build matrix, for
conciseness.
- Switch manylinux1 builds to manylinux2010 (they should still get the
manylinux1 tag if they're compatible, but they'll be built with a more
modern compiler toolchain).
- Move twine upload from .manylinux.sh into .travis.yml's after_success,
right next to the twine upload used for Mac OS builds.
- This means we can't short-circuit the builds with 'exit 0' in
before_install:, so overwrite the install: and script: sections too.
- Move the 'docker pull' from .manylinux.sh into the install: section
so it's not empty.
- Provide twine credentials via environment variables instead of
command-line/pypirc file.
- Put …
> Always build manylinux wheels

- .travis.yml
- docs/README.rst
- docs/adapter.rst
- docs/api/declarations.rst
- docs/api/specifications.rst
- docs/human.rst
- docs/verify.rst
- tox.ini
Fixes #119.
I don't see where Travis CI is running `sphinx-build -b doctest`.  If it doesn't, that seems like a bad oversight (that I don't currently have energy to rectify.  Help, anyone?)
I haven't read the surrounding text closely enough to be sure it still makes sense after my changes.  A close review would be appreciated.
I'm not sure what to do with the code example for `classImplements` that I had to rewrite to use `@implementer` because `classImplements` does not work any more.
If Zope Foundation had any money maybe they could hire a technical writer to clean this up....  (RIP Zope Foundation, long live Plone Foundation!)
> Port the documentation examples to Python 3

- setup.py
The feature was used to optionally disable C extension modules used for speed optimizations.
Nowadays we can disable this extension module by setting the PURE_PYTHON environment variable.
Closes #30. (See https://github.com/pypa/setuptools/issues/65)
> Remove deprecated use of setuptools features

- .travis.yml
3.6.0 encounters https://github.com/nedbat/coveragepy/issues/703
Alternative to #108; other zopefoundation projects have also pinned to a version.
> Use 3.6.2 on Travis.

- CHANGES.rst
- src/zope/interface/_zope_interface_coptimizations.c
- src/zope/interface/declarations.py
- src/zope/interface/interface.py
- src/zope/interface/tests/test_declarations.py
Instead of storing 1 and 2 attributes, respectively, in `__dict__`. This lets us eliminate inst_attr and its use of an undocumented API.
It also helps reign in the size of these objects. Before, on CPython 8, a ClassProvides object that subclasses both SpecificationBase and ClassProvidesBase required 408 bytes: 48 for the object, 360 for the dict.
Now it requires 72 + 232 = 304.
With a bit of work on defining `__slots__` in Python, that can be brought much lower still, I think.
zope.security tests pass with this installed.
The .c file was mostly spaces with a smattering of tabs thrown in; this PR also removes the tabs for consistency so `?w=1` might be helpful.
> Use tp_members in SpecificationBase and ClassProvidesBase; stop using private undoc API

- CHANGES.rst
- src/zope/interface/interface.py
Performance optimization of ``__hash__`` method on ``InterfaceClass``.
The method is called very often (i.e several 100.000 times on a Plone 5.2 startup). 
Even if a single ``hash`` is very fast, this sums up to a real significant part of processing time.
Because the hash value calculated from ``name`` and ``__module__`` never changes (afaik), it can be cached.
I took Py-Spy to analyze the performance.
On reindexing of an index in ZCatalog the ``__hash__`` took ~9 seconds after 10000 samples before changes. 
With a cached hash like in this implementation ``__hash__`` takes ~4.7 seconds.
The whole reindex index process came down from 402s to 320s (1.26x faster).
The test performance ``python setup.py test`` goes from 0.614s down to 0.575s (1.07x faster).
> Improve InterfaceClass __hash__ performance

- CHANGES.rst
- src/zope/interface/_zope_interface_coptimizations.c
- src/zope/interface/declarations.py
- src/zope/interface/interface.py
- src/zope/interface/tests/test_declarations.py
- src/zope/interface/tests/test_interface.py
Details in commit messages. In short:
- Make Declaration, Specification, ClassProvides use `__slots__` or `tp_members`. Shouldn't affect pickling as outlined in #154. Would break sticking arbitrary objects on them, of course.
- Avoid allocating WeakKeyDictionary for dependents unless needed (< 50% of the time)
- Likewise for tagged value storage.
I think these optimizations are safe. Adding `__slots__` to `Element`, `Method` or `Attribute` leads to hard-to-resolve layout or metaclass conflicts, so I didn't touch them. Also, using `__doc__` as an instance variable makes it *really, really* hard to do anything with it.
On loading a sample application[1] of 6000 modules that defined 2200 interfaces, I got a total memory savings of about 6-7% (roughly 235MB to 223MB) from 4.7.1, as measured …
> More memory optimizations for a 6-7% reduction.

- CHANGES.rst
- src/zope/interface/declarations.py
- src/zope/interface/tests/test_declarations.py
> Make the singleton _empty immutable.

- CHANGES.rst
- src/zope/interface/declarations.py
Remove unneeded overwrite and call to anyway inherited `__hash__` method  from `.declarations.Implements` class. 
Watching a reindex index process in ZCatalog with Py-Spy after 10k samples the TotalTime for `.adapter._lookup`  was reduced from 27.5s to 18.8s (~1.5x faster) by taking almost the same OwnTime (before 15.7s/after 13.18s). Before the removed `__hash__` had an OwnTime of 7.76s.
Overall reindex index time  shrunk from 369s to 293s (1.26x faster).
I wonder why this method was necessary? Or is it still for some edge case? 
I am sure it was not placed there w/o a reason.
> Remove unneeded overwrite and call to anyway inherited __hash__ method

- CHANGES.rst
- src/zope/interface/declarations.py
- src/zope/interface/interface.py
- src/zope/interface/tests/test_adapter.py
Turns out they can be called in some very strange error cases. See #162 and #163 for details.
This should fix #162 (at least the provided test case, five.intid, passes now).
It also does enough work on #163 that (a) the test can be written and run in pure-python mode, which was needed to debug it and (b) five.intid runs in pure-python mode (well, with a bunch of other small hacks to Acquisition, ExtensionClass, DocumentTemplate and AccessControl), but I won't claim that it fully resolves that issue. For one thing, there are no specific tests. For another, I see more such differences.
@jensens Does this solve the issues, or at least get you further?
> The _empty singleton has no-op subscribe/unsubscribe methods.

- CHANGES.rst
- src/zope/interface/adapter.py
Micro-optimization in `.adapter._lookup`, `.adapter._lookupAll` and   `.adapter._subscriptions`: By loading components.get into a local variable  before entering the loop a bytcode "LOAD_FAST 0 (components)" in the loop can be eliminated. 
In Plone, while running all tests, average speedup of   `_lookup`s owntime is ~5x (this time measured with py-spy and 35k samples while running all tests)
> Performance optimization in _lookup _lookupAll and _subscriptions

- CHANGES.rst
- src/zope/interface/adapter.py
- src/zope/interface/advice.py
- src/zope/interface/declarations.py
- src/zope/interface/document.py
- src/zope/interface/exceptions.py
- src/zope/interface/interface.py
- src/zope/interface/interfaces.py
- src/zope/interface/registry.py
- src/zope/interface/ro.py
- src/zope/interface/verify.py
Fixes #153
The items that went in each ``__all__`` are based on two thnigs.
First, what is documented:
```console
$ rg --no-filename 'import' docs/ -trst | tr -s "[:blank:]" | sort | uniq | grep zope
>>> from pprint import pprint
>>> from zope.interface import *
>>> from zope.interface import Interface
>>> from zope.interface import Interface, Attribute, implementer
>>> from zope.interface import alsoProvides
>>> from zope.interface import classImplements
>>> from zope.interface import classImplementsOnly
>>> from zope.interface import directlyProvidedBy
>>> from zope.interface import directlyProvides
>>> from zope.interface import implementedBy
>>> from zope.interface import implementer
>>> from zope.interface import implementer_only
>>> from zope.interface import noLongerProvides
>>> …
```
> Add __all__ to all modules.

- CHANGES.rst
- src/zope/interface/_compat.py
- src/zope/interface/common/mapping.py
- src/zope/interface/common/sequence.py
- src/zope/interface/interface.py
- src/zope/interface/tests/test_verify.py
- src/zope/interface/verify.py
On PyPy2, they are ignored (like on CPython), but on PyPy3 they can actually be validated.
Fixes #118
To add tests for this, some minor changes to the common interfaces that remove missing methods on Python 3 were needed.
> Fix verification for methods of builtin types with pseudo-default args on PyPy

- CHANGES.rst
- docs/README.rst
- docs/verify.rst
- src/zope/interface/exceptions.py
- src/zope/interface/interface.py
- src/zope/interface/interfaces.py
- src/zope/interface/tests/test_exceptions.py
- src/zope/interface/tests/test_interface.py
- src/zope/interface/verify.py
Eliminate the trailing newlines and blank spaces (the code called them "a stupid artifact").
Include the name of the defining interface (so the user can easily look up any requirements on the attribute) and, for methods, the expected signature (no more guessing about how many arguments are required!).
This is implemented by giving Attribute and Method useful reprs and strs. Previously, they just had the defaults.
Fixes #170
> Make verification errors more readable and useful.

- .travis.yml
- CHANGES.rst
- docs/verify.rst
- src/zope/interface/exceptions.py
- src/zope/interface/tests/test_exceptions.py
- src/zope/interface/tests/test_verify.py
- src/zope/interface/verify.py
> Make verifyObject/Class collect and raise all errors instead of only the first

- src/zope/interface/tests/test_interface.py
It seems to be working now, so this fixes #6
I tried to reproduce the example by hand in Python 3.8 and 2.7 and couldn't. I don't know what I saw when I commented earlier that it was failing with the C accelerators.
> Add test case for #6.

- CHANGES.rst
- src/zope/interface/interface.py
- src/zope/interface/tests/test_interface.py
and as usual in Python.
It broke tons of tests in Plone and related. Also the repr looks like it's usual in Python.
> Fix repr of "Attribute" to look like before

- CHANGES.rst
- docs/api/common.rst
- src/zope/interface/common/__init__.py
- src/zope/interface/common/builtins.py
- src/zope/interface/common/collections.py
- src/zope/interface/common/io.py
- src/zope/interface/common/mapping.py
- src/zope/interface/common/numbers.py
- src/zope/interface/common/sequence.py
- src/zope/interface/common/tests/__init__.py
- src/zope/interface/common/tests/test_builtins.py
- src/zope/interface/common/tests/test_collections.py
- src/zope/interface/common/tests/test_io.py
- src/zope/interface/common/tests/test_numbers.py
- src/zope/interface/tests/test_verify.py
Derived automatically from Python stdlib ABCs.
When done, this will fix #138. 
So far, its just the collection classes. Remaining items:
> Add more common interfaces

- .travis.yml
- CHANGES.rst
- docs/adapter.rst
- docs/conf.py
- setup.py
- src/zope/interface/_zope_interface_coptimizations.c
- src/zope/interface/adapter.py
- src/zope/interface/declarations.py
- src/zope/interface/tests/test_adapter.py
- src/zope/interface/tests/test_declarations.py
- src/zope/interface/tests/test_registry.py
The query functions now start by looking at the next class in the MRO (interfaces directly provided by the underlying object are not found).
Adapter registries automatically pick up providedBy change to start finding the correct implementations of adapters, but to make that really useful they needed to change to unpack super() arguments and pass `__self__` to the factory.
Fixes #11
Unfortunately, this makes PyPy unable to build the C extensions.
> Make provided/implementedBy and adapter registries respect super().

- CHANGES.rst
- appveyor.yml
- docs/api/declarations.rst
- docs/api/index.rst
- docs/api/ro.rst
- docs/verify.rst
- setup.py
- src/zope/interface/__init__.py
- src/zope/interface/common/__init__.py
- src/zope/interface/common/builtins.py
- src/zope/interface/common/collections.py
- src/zope/interface/common/mapping.py
- src/zope/interface/common/tests/__init__.py
- src/zope/interface/common/tests/test_collections.py
- src/zope/interface/declarations.py
- src/zope/interface/interface.py
- src/zope/interface/interfaces.py
- src/zope/interface/registry.py
- src/zope/interface/ro.py
- src/zope/interface/tests/test_declarations.py
- src/zope/interface/tests/test_interface.py
- src/zope/interface/tests/test_ro.py
Fixes #21
The 'mostly' is because interfaces are used in cases that C3 forbids; when there's a conflict, we move forward by adding the simple legacy base to the list at the conflicting location and continuing.
I hoped the fix for #8 might shake out automatically, but it didn't.
> Use C3 (mostly) to compute IRO.

- CHANGES.rst
- docs/README.rst
- docs/api/declarations.rst
- docs/api/specifications.rst
- src/zope/interface/interface.py
- src/zope/interface/interfaces.py
- src/zope/interface/tests/test_interface.py
Previously it manually walked up __bases__, meaning the answers could be inconsistent.
Fixes #190.
Also fixes several minor issues in the documentation, mostly cross-reference related.
> Make Interface.getTaggedValue follow the __iro__.

- docs/adapter.rst
- src/zope/interface/interfaces.py
- docs/adapter.rst
Subscriptions are returned from least to most specific, not the other way around; the docs were incorrect.
Add additional examples, and use more verbose names in current examples, to clarify this. Fixes #136.
- interfaces.py
names() and namesAndDescriptions() just return a collection, not a sequence. Fixes #134.
> Documentation clarifications.

- CHANGES.rst
- docs/README.rst
- src/zope/interface/common/tests/__init__.py
- src/zope/interface/interface.py
- src/zope/interface/ro.py
- src/zope/interface/tests/test_interface.py
- src/zope/interface/tests/test_ro.py
None of the elegant solutions mentioned in the issue worked out, so I had to brute force it.
Fixes #8
Plone's buildout.coredev tests show no new regressions.
> Ensure Interface is the last item in the __sro__.

- CHANGES.rst
- MANIFEST.in
- benchmarks/micro.py
- src/zope/interface/_compat.py
- src/zope/interface/_zope_interface_coptimizations.c
- src/zope/interface/declarations.py
- src/zope/interface/interface.py
- src/zope/interface/tests/__init__.py
- src/zope/interface/tests/test_declarations.py
- src/zope/interface/tests/test_interface.py
- src/zope/interface/tests/test_registry.py
- src/zope/interface/tests/test_sorting.py
Included benchmark numbers:
Current master, Python 3.8:
```
.....................
contains (empty dict): Mean +- std dev: 198 ns +- 5 ns
.....................
contains (populated dict): Mean +- std dev: 197 ns +- 6 ns
.....................
contains (populated list): Mean +- std dev: 53.1 us +- 1.2 us
```
This code:
```
.....................
contains (empty dict): Mean +- std dev: 77.9 ns +- 2.3 ns
.....................
contains (populated dict): Mean +- std dev: 78.4 ns +- 3.1 ns
.....................
contains (populated list): Mean +- std dev: 3.69 us +- 0.08 us
```
So anywhere from 2.5 to 15x faster. Not sure how that will translate to larger (macro) benchmarks, but I'm hopeful. I also need to do some sorting benchmarks (e.g., using interfaces as keys in BTrees).
To make this work, …
> Move Interface hashing and comparison to C; 2.5 to 15x speedup in micro benchmarks

- .travis.yml
- CHANGES.rst
- src/zope/interface/common/collections.py
- src/zope/interface/common/tests/test_collections.py
- src/zope/interface/interface.py
- src/zope/interface/ro.py
- src/zope/interface/tests/test_interfaces.py
- src/zope/interface/tests/test_ro.py
- tox.ini
Fixes #192 and fixes #194.
Also fix the IRO for OrderedDict on CPython 2. This was necessary to be able to run all the unit tests with STRICT_IRO turned on by default.
> Make the RO for InterfaceClass consistent and fix handling of the STRICT_IRO

- CHANGES.rst
- src/zope/interface/declarations.py
- src/zope/interface/interface.py
- src/zope/interface/tests/test_declarations.py
Fixes #197.
I've confirmed this fixes the zope.traversing tests.
> Ensure that objects that implement no interfaces still have Interface in iro and sro

- CHANGES.rst
- benchmarks/micro.py
- src/zope/interface/_zope_interface_coptimizations.c
- src/zope/interface/declarations.py
- src/zope/interface/interface.py
- src/zope/interface/tests/__init__.py
- src/zope/interface/tests/test_adapter.py
- src/zope/interface/tests/test_declarations.py
- src/zope/interface/tests/test_interface.py
Only catch AttributeError instead of everything.
Fixes #200
Note that this does break a doctest in five.intid (it's expecting a TypeError but it now gets Acquisition's RuntimeError).
> Remove the bare except: statements.

- CHANGES.rst
- docs/README.rst
- docs/api/declarations.rst
- docs/conf.py
- src/zope/interface/__init__.py
- src/zope/interface/_zope_interface_coptimizations.c
- src/zope/interface/common/__init__.py
- src/zope/interface/interface.py
- src/zope/interface/interfaces.py
- src/zope/interface/tests/test_adapter.py
- src/zope/interface/tests/test_declarations.py
- src/zope/interface/tests/test_interface.py
Fixes #3 with no performance penalty (compared to always calling `self.__adapt__`) if this feature is not used. If it is, there's a minimum ~20% penalty, but that's still a lot faster than 4.7.2 (details in #3).
| Benchmark                                                   | Master | self.__adapt()                 | This PR             |
|-------------------------------------------------------------|----------------|------------------------------|------------------------------|
| call interface (provides; deep)                             | 369 ns         | 454 ns: 1.23x slower (+23%)  | not significant              |
| call interface (provides; wide)                             | 373 ns         | 457 ns: 1.22x slower (+22%)  | 365 ns: 1.02x faster (-2%)   |
| call interface (no …
> Let interfaces override __adapt__

- CHANGES.rst
- docs/README.rst
- docs/api/declarations.rst
- src/zope/interface/declarations.py
- src/zope/interface/tests/test_declarations.py
- src/zope/interface/tests/test_registry.py
The plone buildout.coredev tests all pass, with the exception of 8 tests from `plone.app.caching.tests.test_etags`. They all fail like this:
```
Error in test test_Roles_member (plone.app.caching.tests.test_etags.TestETags)
Traceback (most recent call last):
File "//2.7/lib/python2.7/unittest/case.py", line 329, in run
testMethod()
File "//plone.app.caching-2.0.4-py2.7.egg/plone/app/caching/tests/test_etags.py", line 144, in test_Roles_member
provideAdapter(DummyPortalState, name=u'plone_portal_state')
File "//zope.component-4.5-py2.7.egg/zope/component/globalregistry.py", line 73, in provideAdapter
base.registerAdapter(factory, adapts, provides, name, event=False)
File "//src/zope.interface/src/zope/interface/registry.py", line 305, in registerAdapter
provided = …
```
> Make @implementer and classImplements not add redundant interfaces

- CHANGES.rst
- src/zope/interface/adapter.py
- src/zope/interface/interfaces.py
- src/zope/interface/tests/test_adapter.py
They were defined to accept a name argument, but the actual implementation doesn't. Add tests for this. Fixes #208.
Also in test_adapter.py modernize idioms from `assertTrue(x in y)` and `assertTrue(x is y)` to `assertIn` and `assertIs`.
> Fix interface definitions of IAdapterRegistry.subscribe, subscribers, subscriptions

- CHANGES.rst
- docs/api/specifications.rst
- src/zope/interface/_zope_interface_coptimizations.c
- src/zope/interface/tests/test_declarations.py
Previously they did not, leading to a reference leak of a tuple.
Fixes #216
> C optimizations: Spec_clear and Spec_traverse need to include Spec->_bases

- .gitignore
- CHANGES.rst
- src/zope/interface/interface.py
- src/zope/interface/tests/test_interface.py
When an invariant is defined in an interface, it's found by `validateInvariants` in all interfaces inheriting from that interface.
> Make sure to call each invariant only once when validating invariants.

- CHANGES.rst
- docs/README.rst
- docs/api/specifications.rst
> Document persistency and equality

- .manylinux-install.sh
- .travis.yml
Added support for arm64 wheel development.
Modified .manylinux-install.sh to add tox support for arm64.
Related to #214 
@jamadden Please review.
> Add support for arm64 wheel

- CHANGES.rst
- docs/api/adapters.rst
- docs/conf.py
- src/zope/interface/adapter.py
- src/zope/interface/tests/test_adapter.py
- src/zope/interface/tests/test_registry.py
Add extensive tests for this. Fixes #224.
Also adds test for, and fixes #227
Based on #226 so that CI runs. The first two commits aren't relevant to this PR.
I'd like to add a migration method to help existing persistent utilities convert to new data structures, but before that's done I'll open this as a draft so the general approach can be looked at.
> Let subclasses of BaseAdapterRegistry customize the data structures.

- docs/README.rst
- docs/api/specifications.rst
- src/zope/interface/adapter.py
- src/zope/interface/declarations.py
- src/zope/interface/interface.py
- src/zope/interface/tests/test_adapter.py
This should help provide better motivating use cases compared to the what the docs called the "silly" example of converting one number to another. 
Examples inspired by https://glyph.twistedmatrix.com/2021/03/interfaces-and-protocols.html
Also some minor typo fixes and updates to comments. (One of which is for https://github.com/zopefoundation/zope.component/pull/53.)
> Update the Adaptation docs to be more concrete.

- CHANGES.rst
- src/zope/interface/declarations.py
- src/zope/interface/interface.py
- src/zope/interface/tests/test_declarations.py
This is the last PR I'm hoping to merge before making a release.
cf #207
> Make Provides and ClassProvides ignore redundant interfaces like @implementer

- CHANGES.rst
- src/zope/interface/declarations.py
- src/zope/interface/ro.py
- src/zope/interface/tests/test_declarations.py
> Update documentation and Provides repr for better debugging.

- CHANGES.rst
- docs/README.rst
- docs/api/declarations.rst
- docs/verify.rst
- src/zope/interface/declarations.py
- src/zope/interface/interface.py
- src/zope/interface/tests/test_declarations.py
- src/zope/interface/tests/test_exceptions.py
- src/zope/interface/tests/test_ro.py
Only InterfaceClass got a str, so it now has a distinction. Other objects only got updated reprs.
Note: This may potentially break some doctests.
In many cases, the ``repr()`` is now something that can be evaluated to produce an equal object. For example, what was previously printed as ``<implementedBy builtins.list>`` is now shown as ``classImplements(list, IMutableSequence, IIterable)``.
Fixes #236
Here's a before with ZOPE_INTERFACE_LOG_CHANGED_IRO=1 in BTrees:
```
Object <implementedBy builtins.list> has different legacy and C3 MROs:
Legacy RO (len=11)                                                        C3 RO (len=11; inconsistent=no)
================================================================================================================================================== …
```
> Update repr() and str() of some common objects.

- CHANGES.rst
- docs/api/declarations.rst
- src/zope/interface/declarations.py
- src/zope/interface/tests/test_declarations.py
By moving things from the RHS to the front of the list if they already extend something from the LHS.
Fixes #193
The [changes in the documentation](https://github.com/zopefoundation/zope.interface/compare/issue193?expand=1#diff-8ef5cd6985c269c8fa159314befb6fc8082c919e8f75727958b7e2fa36e2294a) are a good example of the kind of weird things that used to happen but which should now make more sense. Previously, you could get `IRoot2` ahead of `IDerived2`, which is inconsistent.
I'm not 100% positive this covers all possible cases (deeply nested hierarchies, branching at weird places) but it does fix the easy/common ones that I've seen in the real world. It can be improved as needed given further examples.
> Make Declaration.__add__ try harder to produce consistent resolution orders

- CHANGES.rst
- src/zope/interface/_zope_interface_coptimizations.c
- src/zope/interface/declarations.py
- src/zope/interface/tests/test_declarations.py
Fixes #239
There was a similar bug in the Python side where it would ignore a `__provides__` of None, unlike the C implementation.
I fixed this and documented this fix in the code but not the CHANGES.rst because I can't imagine anyone relying on that.
> Make C's __providedBy__ stop ignoring all errors and catch only AttributeError

- .github/workflows/tests.yml
- docs/api/declarations.rst
- docs/verify.rst
- tox.ini
See #241 for the list of failures occurring previously.
Closes #241.
> Fix the documentation so it can be tested with `ZOPE_INTERFACE_STRICT_IRO=1`.

- .meta.toml
- appveyor.yml
(I cheated and edited both files manually instead of editing .meta.toml
and re-running the config tool.)
See https://github.com/zopefoundation/meta/issues/109
> Use a token for twine uploads from Appveyor

- CHANGES.rst
- src/zope/interface/interfaces.py
`ComponentLookupError`, `Invalid`, `Registered`, and `Unregistered` are
all documented
(https://zopeinterface.readthedocs.io/en/latest/api/components.html), so
it seems odd not to list them in `__all__`.  `ObjectEvent` isn't
documented there, but it seems reasonable to export it as a base class
for similar events.
> Add some more entries to zope.interface.interfaces.__all__

- src/zope/interface/common/tests/__init__.py
On PyPy3 the following `registered_classes` for `IMutableMapping` are
found:
```
{<class 'dict'>,
<class 'pkg_resources._vendor.pyparsing.ParseResults'>,
<class 'setuptools._vendor.pyparsing.ParseResults'>,
<class 'collections.UserDict'>}
```
So collecting the tests fails because of a duplicate name which is prevented by this PR.
I have no idea why this does not happen for other Python versions.
Fixes #254.
> Fix tests for PyPy3.

- .github/workflows/tests.yml
- .meta.toml
- src/zope/interface/tests/test_compile_flags.py
- tox.ini
Add a regression test for CFLAGS not having -Ofast, which is known to break things.  See https://github.com/zopefoundation/meta/pull/155 for reference.
Again, I was unable to confirm the regression test locally with
```
$ CFLAGS=-Ofast tox -re py38 -- -k test_no_fast_math_optimization
```
> Update to the latest c-code template

- CHANGES.rst
- src/zope/interface/tests/test_ro.py
Python 3.11 warns:
DeprecationWarning: It is deprecated to return a value that is not
None from a test case (<bound method Test_c3_ro.test_complex_diamond
of <zope.interface.tests.test_ro.Test_c3_ro
testMethod=test_complex_diamond>>)
Rearrange slightly to avoid this.
> Fix test deprecation warning on Python 3.11

- src/zope/interface/declarations.py
The signature of `declarations.Provides` is given as `*interfaces`. This is wrong; it actually is `cls, *interfaces` where *cls* is the class of the instance for which `Provides` should provide a declaration. This parameter is necessary to avoid the construction of inconsistent resolution orders.
The PR does not change the code but improves the `Provides` docstring and especially documents the correct signature there.
> improve `declarations.Provides` documentation

- src/zope/interface/tests/test_document.py
In Python 3.13, compiler strips indents from docstrings. See https://github.com/python/cpython/issues/81283
Fixes: https://github.com/zopefoundation/zope.interface/issues/279
> Make test_document compatible with Python 3.13

- CHANGES.rst
- src/zope/interface/interface.py
- src/zope/interface/tests/test_interface.py
> Add support to use the pipe (`|`) syntax for `typing.Union`.

- CHANGES.rst
- src/zope/interface/interface.py
> Ignore `__static_attributes__` added in Python 3.13a6.

- CHANGES.rst
- src/zope/interface/_compat.py
- src/zope/interface/interface.py
- src/zope/interface/tests/test_advice.py
Fixes #292 
In case you are wondering, the question marks next to the original comparison ``f_locals is locals()`` have existed since at least 2007 when the code was moved to GitHub. I am guessing the original author thought this identity test is questionable.
> Adjust for incompatible changes in Python 3.13b1

- .github/workflows/tests.yml
- .meta.toml
The first try didn't work because the selected GH action doesn't work on Windows. This change re-uses the way we have done it for macOS and applies that to Windows.
> New attempt at fixing missing Windows wheels

- CHANGES.rst
- src/zope/interface/_zope_interface_coptimizations.c
- src/zope/interface/tests/__init__.py
- src/zope/interface/tests/test_declarations.py
- src/zope/interface/tests/test_interface.py
Broken in 7.0 release.
Closes #312.
> fix: ensure OSD is sublcassable

- CHANGES.rst
- src/zope/interface/_zope_interface_coptimizations.c
Fixes #316 
PyModule_AddObject steals a reference, so we have to Py_INCREF the values that we are passing to it but also owned by the _zic_module_state.
> Fix refcounting bug in module initialization

- CHANGES.rst
- src/zope/interface/common/tests/test_collections.py
Related to #323 
The original issue, a segmentation fault, was fixed between Python 3.13rc2 and rc3. This PR applies a proposed patch by @vstinner in https://github.com/zopefoundation/zope.interface/issues/323#issuecomment-2374076122 to fix a followup issue.
> Fix segmentation fault and FrameLocalsProxy check

- .github/workflows/tests.yml
- .manylinux-install.sh
- .meta.toml
- CHANGES.rst
- pyproject.toml
- src/zope/interface/_compat.py
- src/zope/interface/common/builtins.py
- src/zope/interface/common/collections.py
- src/zope/interface/common/tests/test_builtins.py
- src/zope/interface/interface.py
- tox.ini
I hacked something together so the tests do not fail for Python 3.14.
But I am completly unsure if this is the way we want/should go.
Fixes #334.
> Preliminary support for Python 3.14a2.

- .github/workflows/tests.yml
- .manylinux-install.sh
- .meta.toml
- .pre-commit-config.yaml
- CHANGES.rst
- pyproject.toml
- tox.ini
> Update to setuptools 75.6.0
